# Generated by Django 3.2 on 2022-11-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('parents', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('creditID', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('bedID', models.CharField(max_length=200)),
                ('roomID', models.CharField(max_length=200)),
                ('patient_id', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('foot', models.CharField(max_length=200)),
                ('complications', models.CharField(blank=True, max_length=200)),
                ('tips', models.TextField(blank=True)),
            ],
        ),
    ]
