# Generated by Django 3.2 on 2022-11-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='complications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
