# Generated by Django 3.2 on 2022-11-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20221119_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionentry',
            name='complications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionentry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_entries', to='patients.patient'),
        ),
    ]
