# Generated by Django 3.2 on 2022-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_creditid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='foot',
            field=models.ImageField(blank=True, null=True, upload_to='footprints'),
        ),
    ]
