# Generated by Django 3.2 on 2022-12-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20221209_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='foot',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
