# Generated by Django 3.2 on 2022-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infusions', '0002_alter_infusionentry_perm_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infusionentry',
            name='end_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='infusionentry',
            name='start_time',
            field=models.CharField(max_length=200),
        ),
    ]
