# Generated by Django 3.2 on 2022-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infusions', '0003_auto_20221109_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infusionentry',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='infusionentry',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
