# Generated by Django 3.2 on 2022-11-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infusions', '0004_auto_20221109_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infusionentry',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
