# Generated by Django 3.2 on 2022-11-19 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infusions', '0005_alter_infusionentry_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infusionentry',
            name='performer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_infusion_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infusionentry',
            name='perm_group',
            field=models.ManyToManyField(blank=True, related_name='perm_infusion_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
